## Advance Numpy

In [2]:
import time
import sys
a = [i for i in  range(1000000)]
b = [i for i in  range(1000000,2000000)]
sys.getsizeof(a)

8448728

In [ ]:
import numpy as np
a = np.arange(1000000,dtype=np.int32)
a = np.arange(1000000,dtype=np.int8)
b = np.arange(1000000,1000000)
sys.getsizeof(a)

4000112

In [4]:
8448728/4000112

2.1121228605599045

## Advance Indexing and Broadcasting

In [21]:
ohlc1=np.array([
    [100.0,101.5,99.5,101.0],
    [101.0,102.0,100.5,101.8],
    [101.8,103,101.0,102.5]
])
ohlc2=np.array([
    [200.0,201.5,299.5,201.0],
    [201.0,202.0,200.5,201.8],
    [201.8,203,201.0,202.5],
    [201.8,203,201.0,202.5]
])

In [9]:
ohlc1[1,2]
ohlc1[1:,2:]
ohlc1[[1],[2]]
ohlc1[1:,[2,3]]

array([[100.5, 101.8],
       [101. , 102.5]])

## Fancy Indexing

In [11]:
ohlc2[[0,3],1:3]

array([[201.5, 299.5],
       [203. , 201. ]])

## Boolean Fancy

In [14]:
ohlc1>102
ohlc1[ohlc1>102]

array([103. , 102.5])

In [16]:
ohlc2>102
ohlc2[ohlc2>202]

array([299.5, 203. , 202.5, 203. , 202.5])

In [18]:
ohlc1 % 2==0
ohlc1[ohlc1 % 2==0]

array([100., 102.])

In [24]:
ohlc2[(ohlc2 % 2==0.0) & (ohlc2> 201)]

array([202.])

## Boradcasting

In [26]:
ohlc3=np.array([
    [100.0,101.5,99.5,101.0],
    [101.0,102.0,100.5,101.8],
    [101.8,103,101.0,102.5]
])
ohlc4=np.array([
    [200.0,201.5,299.5,201.0]
])

In [27]:
ohlc3+ohlc4

array([[300. , 303. , 399. , 302. ],
       [301. , 303.5, 400. , 302.8],
       [301.8, 304.5, 400.5, 303.5]])

## More e.g on Broadcasting

In [29]:
a=np.arange(12).reshape(3,4)

In [32]:
b=np.arange(4).reshape(1,4)

In [33]:
a+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

## Working with Mathematical Operatios

In [34]:
np.sin(ohlc1)

array([[-0.50636564,  0.82433986, -0.85779535,  0.45202579],
       [ 0.45202579,  0.99482679, -0.03095997,  0.95481453],
       [ 0.95481453,  0.62298863,  0.45202579,  0.92174542]])

In [37]:
#sigmoid-it is used for normalised the values which are higher
1/(1+np.exp(-(ohlc1)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
#mean squared error
def msc(ohlc3,ohlc4):
    return np.mean((ohlc3-ohlc4)**2)
msc(ohlc3,ohlc4)

np.float64(17299.406666666666)

## Working with Missing Values

In [44]:
ohlc5=np.array([
    [100.0,101.5,np.nan,101.0],
    [101.0,102.0,np.nan,101.8],
    [101.8,103,101.0,102.5]
])

In [45]:
ohlc5

array([[100. , 101.5,   nan, 101. ],
       [101. , 102. ,   nan, 101.8],
       [101.8, 103. , 101. , 102.5]])

In [46]:
np.isnan(ohlc5)

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [47]:
~np.isnan(ohlc5)

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [48]:
ohlc5[~np.isnan(ohlc5)]

array([100. , 101.5, 101. , 101. , 102. , 101.8, 101.8, 103. , 101. ,
       102.5])