## Numpy

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([[1,2,3], [2,2,2]])

array([[1, 2, 3],
       [2, 2, 2]])

In [5]:
# dtype
np.array([1,2,3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [ ]:
# str
np.array([1,2,3], dtype=str)

array(['1', '2', '3'], dtype='<U1')

In [9]:
#arange
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# reshape
np.arange(0,12).reshape(2,6)
np.arange(0,12).reshape(2,2,3)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
#np.ones
np.ones((6))
np.ones((2,2))
np.ones((2,2,3))

array([[1., 1.],
       [1., 1.]])

In [14]:
#np.zeros
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#np.random
np.random.random((3,4))

array([[0.42025487, 0.39149171, 0.48415331, 0.53356482],
       [0.80835677, 0.46226384, 0.11119439, 0.31551544],
       [0.04518628, 0.23530032, 0.90381374, 0.79644369]])

In [19]:
#np.linespace
np.linspace(1,10,10)
np.linspace(1,10,3)
np.linspace(1,100,25)

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [20]:
#np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [29]:
a1=np.array([1,2,3],dtype=np.int32)
a2=np.array([[1,2,3],[1,2,3]])
a3=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [24]:
#ndim
a3.ndim

3

In [25]:
#shape
a1.shape

(3,)

In [26]:
#size
a1.size

3

In [27]:
#itemsize
a1.itemsize

8

In [30]:
#
a1.itemsize

4

## Changing Datatype

In [31]:
#astype
a3.astype(np.int32)

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)

## Big Normal Examples

In [43]:
ohlc_data_day1=np.array([
    [100.0,101.5,99.5,101.0],
    [101.0,102.0,100.5,101.8],
    [101.8,103,101.0,102.5]
])
ohlc_data_day2=np.array([
    [200.0,201.5,299.5,201.0],
    [201.0,202.0,200.5,201.8],
    [201.8,203,201.0,202.5],
    [201.8,203,201.0,202.5]
])

In [33]:
import numpy as np

In [36]:
np.max(ohlc_data_day1)
np.min(ohlc_data_day1)
np.sum(ohlc_data_day1)

np.float64(1215.6)

In [37]:
# scaler operations
ohlc_data_day1*2

array([[200. , 203. , 199. , 202. ],
       [202. , 204. , 201. , 203.6],
       [203.6, 206. , 202. , 205. ]])

In [38]:
#relational
ohlc_data_day1 == 100

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [39]:
# vector operations arthimetic
ohlc_data_day1 * ohlc_data_day2

array([[20000.  , 20452.25, 29800.25, 20301.  ],
       [20301.  , 20604.  , 20150.25, 20543.24],
       [20543.24, 20909.  , 20301.  , 20756.25]])

In [ ]:
#mean/median/std/var
np.mean(ohlc_data_day1)
np.median(ohlc_data_day1)
np.std(ohlc_data_day1)
np.var(ohlc_data_day1)

np.float64(101.3)

In [42]:
#Trignometric functions
np.cos(ohlc_data_day1)

array([[ 0.86231887,  0.56609521,  0.51399138,  0.89200487],
       [ 0.89200487,  0.1015857 ,  0.99952063,  0.29720233],
       [ 0.29720233, -0.78223089,  0.89200487, -0.38779553]])

In [45]:
#dot_product
# col of 1st metric should be equal to rows second metric
np.dot(ohlc_data_day1,ohlc_data_day2)

array([[80862.4 , 81354.5 , 90601.25, 81183.95],
       [81526.14, 82022.4 , 91362.8 , 81850.35],
       [82129.3 , 82629.2 , 92044.1 , 82455.95]])

In [46]:
#log and exponents
np.exp(ohlc_data_day1)

array([[2.68811714e+43, 1.20473052e+44, 1.63042546e+43, 7.30705998e+43],
       [7.30705998e+43, 1.98626484e+44, 4.43195591e+43, 1.62621611e+44],
       [1.62621611e+44, 5.39922761e+44, 7.30705998e+43, 3.27479708e+44]])

In [49]:
#round/floor/ceil
np.round(ohlc_data_day1)
np.floor(ohlc_data_day1)
np.ceil(ohlc_data_day1)

array([[100., 102., 100., 101.],
       [101., 102., 101., 102.],
       [102., 103., 101., 103.]])

## Indexing


In [50]:
a5=[1,2,3,4,5]

In [52]:
a5[0]
a5[1:4]

[2, 3, 4]

In [57]:
ohlc_data_day1[0,:]
ohlc_data_day1[:,3]
ohlc_data_day1[1,:]
ohlc_data_day1[1:,1:3]

array([[102. , 100.5],
       [103. , 101. ]])

### Indexing & Slicing of 3d array

In [59]:
threedarray=np.arange(0,24).reshape(2,3,4)

In [61]:
threedarray[0]
threedarray[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
#
threedarray[0,1:,1:3]
threedarray[1,:,2:]

array([[14, 15],
       [18, 19],
       [22, 23]])

In [67]:
threedarray[:,::2]

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [20, 21, 22, 23]]])

## Iterating

In [70]:
a6=[1,2,3,4,5]
for i in a6:
    print(i)

1
2
3
4
5


In [71]:
for i in ohlc_data_day1:
    print(i)

[100.  101.5  99.5 101. ]
[101.  102.  100.5 101.8]
[101.8 103.  101.  102.5]


In [72]:
for i in np.nditer(ohlc_data_day1):
    print(i)

100.0
101.5
99.5
101.0
101.0
102.0
100.5
101.8
101.8
103.0
101.0
102.5


In [74]:
for i in np.ravel(ohlc_data_day1):
    print(i)

100.0
101.5
99.5
101.0
101.0
102.0
100.5
101.8
101.8
103.0
101.0
102.5


## Reshaping

In [76]:
np.arange(0,24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
np.arange(0,24).reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
np.transpose(ohlc_data)

In [ ]:
#Transpose
np.trans

In [ ]:
#

In [ ]:
#